#!/usr/bin/env bash
# install nginx on web-01

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
