#!/usr/bin/env bash
# Bash script that configures a server to the above requirements
# Nginx must be running, and listening on port 80

apt-get update
apt-get install -y nginx

service nginx stop

sed -i 's/^ *listen *.*$/listen 80;/g' /etc/nginx/sites-available/default

service nginx start
