#!/usr/bin/env bash
# Write a Bash script that
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself
#when receiving a SIGQUIT or SIGTERM signal

cleanup() {
    echo "Deleting PID file and terminating script..."
    rm -f /var/run/myscript.pid
    exit
}

# Registering cleanup function for SIGQUIT and SIGTERM signals
trap 'cleanup' SIGQUIT SIGTERM

# Function to handle SIGINT signal
sigint_handler() {
    echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I hate the kill command"
}

# Registering sigint_handler function for SIGINT signal
trap 'sigint_handler' SIGINT

# Registering sigterm_handler function for SIGTERM signal
trap 'sigterm_handler' SIGTERM

# Get the PID of the current script and save it to the PID file
echo $$ > /var/run/myscript.pid

# Infinite loop displaying "To infinity and beyond"
while true; do
    echo "To infinity and beyond"
    sleep 1
done
